"""add order courier aggregates

Revision ID: 36c86de93470
Revises:
Create Date: 2025-06-29 15:50:55.634394

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36c86de93470"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "couriers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("order_status", sa.String(length=20), nullable=False),
        sa.Column("courier_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "storage_places",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("total_volume", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courier_storage_places",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("courier_id", sa.UUID(), nullable=False),
        sa.Column("storage_place_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storage_place_id"],
            ["storage_places.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courier_storage_places")
    op.drop_table("storage_places")
    op.drop_table("orders")
    op.drop_table("couriers")
    # ### end Alembic commands ###
