# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrastructure/adapters/grpc/geo/Contract.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'infrastructure/adapters/grpc/geo/Contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/infrastructure/adapters/grpc/geo/Contract.proto\x12\x03geo\"\'\n\x15GetGeolocationRequest\x12\x0e\n\x06Street\x18\x01 \x01(\t\"6\n\x13GetGeolocationReply\x12\x1f\n\x08Location\x18\x01 \x01(\x0b\x32\r.geo.Location\" \n\x08Location\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1d\n\rErrorResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2M\n\x03Geo\x12\x46\n\x0eGetGeolocation\x12\x1a.geo.GetGeolocationRequest\x1a\x18.geo.GetGeolocationReplyB\x1bZ\x0cgeosrv/geopb\xaa\x02\nGeoApp.Apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrastructure.adapters.grpc.geo.Contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014geosrv/geopb\252\002\nGeoApp.Api'
  _globals['_GETGEOLOCATIONREQUEST']._serialized_start=56
  _globals['_GETGEOLOCATIONREQUEST']._serialized_end=95
  _globals['_GETGEOLOCATIONREPLY']._serialized_start=97
  _globals['_GETGEOLOCATIONREPLY']._serialized_end=151
  _globals['_LOCATION']._serialized_start=153
  _globals['_LOCATION']._serialized_end=185
  _globals['_ERRORRESPONSE']._serialized_start=187
  _globals['_ERRORRESPONSE']._serialized_end=216
  _globals['_GEO']._serialized_start=218
  _globals['_GEO']._serialized_end=295
# @@protoc_insertion_point(module_scope)
